version: '3.7'
services:
  ai-api:
    image: www.ebl.lmu.de/ebl-ai-api:main
    networks:
     - ebl-api
    logging:
      driver: json-file
    deploy:
      labels:
        swarmpit.service.deployment.autoredeploy: 'true'
      resources:
        limits:
          cpus: '1.0'
          memory: 2048M
  api:
    image: www.ebl.lmu.de/ebl-api:master
    command: 'pipenv run waitress-serve --port=8000 --threads=6 --call ebl.app:get_app'
    environment:
      AUTH0_AUDIENCE: dictionary-api
      AUTH0_ISSUER: https://electronic-babylonian-literature.eu.auth0.com/
      AUTH0_PEM: <Auth0 PEM>
      CACHE_CONFIG: '{"CACHE_TYPE": "redis", "CACHE_REDIS_HOST": "redis"}'
      MONGODB_URI: mongodb://<user>:<password>@lmkwitg-ebl01.srv.mwn.de:27017,lmkwitg-ebl02.srv.mwn.de:27018/ebl?replicaSet=rs-ebl1&tls=true&tlsCAFile=/run/secrets/mongoCA.crt
      SENTRY_DSN: <Sentry DSN>
      SENTRY_ENVIRONMENT: production
      EBL_AI_API: http://ai-api:8001
      CORRECTIONS_EMAIL: ebl-support+corrections@culture.lmu.de
    secrets:
     -
      source: mongoCA.crt
      uid: '999'
      gid: '999'
      mode: 0400
    networks:
     - ebl-api
     - traefik-public
    deploy:
      replicas: 2
      labels:
        swarmpit.service.deployment.autoredeploy: 'true'
        traefik.tags: traefik-public
        traefik.docker.network: traefik-public
        traefik.enable: 'true'
        traefik.port: '8000'
        traefik.frontend.rule: PathPrefixStrip:/api/
      resources:
        limits:
          cpus: '1.5'
          memory: 10G
  frontend:
    image: www.ebl.lmu.de/ebl-frontend:master
    networks:
     - traefik-public
    logging:
      driver: json-file
    deploy:
      replicas: 2
      labels:
        swarmpit.service.deployment.autoredeploy: 'true'
        traefik.tags: traefik-public
        traefik.docker.network: traefik-public
        traefik.enable: 'true'
        traefik.port: '5000'
        traefik.frontend.rule: PathPrefix:/
  redis:
    image: redis:6-alpine
    command:
     - redis-server
     - --save
     - ''
     - --maxmemory
     - 900M
     - --maxmemory-policy
     - volatile-ttl
     - --loglevel
     - notice
     - --logfile
     - ''
    networks:
     - ebl-api
     - monitoring
    logging:
      driver: json-file
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1024M
networks:
  ebl-api:
    driver: overlay
  traefik-public:
    external: true
secrets:
  mongoCA.crt:
    external: true
