version: '3.7'
services:
  ai-api:
    image: ebl.badw.de/ebl-ai-api:main
    networks:
     - ebl-api
    logging:
      driver: json-file
    deploy:
      labels:
        swarmpit.service.deployment.autoredeploy: 'true'
      resources:
        limits:
          cpus: '1.0'
          memory: 2048M
  api:
    image: ebl.badw.de/ebl-api:master
    command:
     - poetry
     - run
     - waitress-serve
     - --port=8000
     - --threads=12
     - --call
     - ebl.app:get_app
    environment:
      AUTH0_AUDIENCE: dictionary-api
      AUTH0_ISSUER: https://auth.ebl.lmu.de/
      AUTH0_PEM: <Auth0 PEM>
      CACHE_CONFIG: '{"CACHE_TYPE": "redis", "CACHE_REDIS_HOST": "redis"}'
      EBL_AI_API: http://ai-api:8001
      MONGODB_URI: mongodb://ebl-api:<top_secret_password>@badwcai-ebl01.srv.mwn.de:27017,badwcai-ebl02.srv.mwn.de:27018,badwcai-ebl03.srv.mwn.de:27019/ebl?replicaSet=rs-ebl&tls=true&tlsCAFile=/run/secrets/mongoCA.crt
      NEW_RELIC_CONFIG_FILE: newrelic.ini
      NEW_RELIC_LICENSE_KEY: <key>
      SENTRY_DSN: <Sentry DSN>
      SENTRY_ENVIRONMENT: production
    secrets:
     - mongoCA.crt
    networks:
     - ebl-api
     - traefik-public
    deploy:
      replicas: 3
      labels:
        swarmpit.service.deployment.autoredeploy: 'true'
        traefik.tags: traefik-public
        traefik.docker.network: traefik-public
        traefik.enable: 'true'
        traefik.port: '8000'
        traefik.frontend.rule: PathPrefixStrip:/api/
      resources:
        limits:
          cpus: '2.5'
          memory: 10G
  frontend:
    image: ebl.badw.de/ebl-frontend:master
    networks:
     - traefik-public
    logging:
      driver: json-file
    deploy:
      replicas: 3
      labels:
        swarmpit.service.deployment.autoredeploy: 'true'
        traefik.tags: traefik-public
        traefik.docker.network: traefik-public
        traefik.enable: 'true'
        traefik.port: '5000'
        traefik.frontend.rule: PathPrefix:/
  redis:
    image: redis:6-alpine
    command:
     - redis-server
     - --save
     - ''
     - --maxmemory
     - 900M
     - --maxmemory-policy
     - volatile-ttl
     - --loglevel
     - notice
     - --logfile
     - ''
    networks:
     - ebl-api
     - monitoring
    logging:
      driver: json-file
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1024M
networks:
  ebl-api:
    driver: overlay
  monitoring:
    external: true
  traefik-public:
    external: true
secrets:
  mongoCA.crt:
    external: true
