version: '3.7'
services:
  api:
    image: registry.cluster.ebabylon.org/ebl-api:master
    command: 'pipenv run waitress-serve --port=8000 --threads=6 --call ebl.app:get_app'
    environment:
      AUTH0_AUDIENCE: dictionary-api
      AUTH0_ISSUER: https://auth.ebabylon.org/
      AUTH0_PEM: <Auth0 PEM>
      MONGODB_URI: mongodb://<user>:<password>@lmkwitg-ebl01.srv.mwn.de:27017,lmkwitg-ebl02.srv.mwn.de:27018/ebl?replicaSet=rs-ebl1&ssl=true&ssl_ca_certs=/run/secrets/mongoCA.crt
      SENTRY_DSN: <Sentry DSN>
      SENTRY_ENVIRONMENT: production
    secrets:
     -
      source: mongoCA.crt
      uid: '999'
      gid: '999'
      mode: 0400
    networks:
     - traefik-public
    deploy:
      replicas: 2
      labels:
        traefik.tags: traefik-public
        traefik.redirectorservice.frontend.redirect.entryPoint: https
        traefik.webservice.frontend.entryPoints: https
        swarmpit.service.deployment.autoredeploy: 'true'
        traefik.redirectorservice.frontend.entryPoints: http
        traefik.docker.network: traefik-public
        traefik.enable: 'true'
        traefik.port: '8000'
        traefik.frontend.rule: Host:api.ebabylon.org
      resources:
        limits:
          cpus: '1.5'
          memory: 2G
  frontend:
    image: registry.cluster.ebabylon.org/ebl-frontend:master
    networks:
     - traefik-public
    logging:
      driver: json-file
    deploy:
      replicas: 2
      labels:
        traefik.tags: traefik-public
        traefik.redirectorservice.frontend.redirect.entryPoint: https
        traefik.webservice.frontend.entryPoints: https
        swarmpit.service.deployment.autoredeploy: 'true'
        traefik.redirectorservice.frontend.entryPoints: http
        traefik.docker.network: traefik-public
        traefik.enable: 'true'
        traefik.port: '5000'
        traefik.frontend.rule: Host:www.ebabylon.org
networks:
  traefik-public:
    external: true
secrets:
  mongoCA.crt:
    external: true
