version: '3.7'
services:
  mongo1:
    image: mongo:latest
    command: --replSet rs-ebl1 --sslMode requireSSL --sslPEMKeyFile /run/secrets/ebl01.pem --clusterAuthMode x509 --sslCAFile /run/secrets/mongoCA.crt --sslAllowConnectionsWithoutCertificates
    ports:
     - 27017:27017
    volumes:
     - db1:/data/db
    secrets:
    secrets:
     -
      source: mongoCA.crt
      uid: '999'
      gid: '999'
      mode: 0400
     -
      source: ebl01.pem
      uid: '999'
      gid: '999'
      mode: 0400
    deploy:
      placement:
        constraints:
         - node.hostname == lmkwitg-ebl01
      resources:
        limits:
          cpus: '1.5'
          memory: 4G
  mongo2:
    image: mongo:latest
    command: --replSet rs-ebl1 --sslMode requireSSL --sslPEMKeyFile /run/secrets/ebl02.pem --clusterAuthMode x509 --sslCAFile /run/secrets/mongoCA.crt --sslAllowConnectionsWithoutCertificates
    ports:
     - 27018:27017
    volumes:
     - db2:/data/db
    secrets:
     -
      source: mongoCA.crt
      uid: '999'
      gid: '999'
      mode: 0400
     -
      source: ebl02.pem
      uid: '999'
      gid: '999'
      mode: 0400
    deploy:
      placement:
        constraints:
         - node.hostname == lmkwitg-ebl02
      resources:
        limits:
          cpus: '1.5'
          memory: 4G
volumes:
  db1:
    driver: local
  db2:
    driver: local
secrets:
  mongoCA.crt:
    external: true
  ebl01.pem:
    external: true
  ebl02.pem:
    external: true
