version: 0.1
log:
  fields:
    service: registry
storage:
  cache:
    blobdescriptor: inmemory
  filesystem:
    rootdirectory: /var/lib/registry
  delete:
    enabled: true
http:
  addr: :5000
  headers:
    X-Content-Type-Options: [nosniff]
notifications:
  endpoints:
    - name: docker-registry-ui
      url: https://ebl.badw.de/cluster/registry-ui/api/events
      headers:
        Authorization: [Bearer <same token as in docker-registry-ui_config.yml>]
      timeout: 1s
      threshold: 5
      backoff: 10s
      ignoredmediatypes:
        - application/octet-stream
