constraints = ["tag==traefik-public"]
logLevel = "INFO"
defaultEntryPoints = ["http", "https"]


[accessLog]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
  compress = true
    [entryPoints.https.tls]
    minVersion = "VersionTLS12"
      

[acme]
email = "jussi.laasonen@lmu.de"
storage = "traefik/acme/account"
entryPoint = "https"
acmeLogging = true
onHostRule = true

[acme.httpChallenge]
entryPoint = "http"

[[acme.domains]]
  main = "www.ebl.lmu.de"
[[acme.domains]]
  main = "www.ebl.uni-muenchen.de"


[docker]
watch = true
swarmMode = true
exposedByDefault = false


[consul]
endpoint = "consul-leader:8500"


[api]


[metrics]
  [metrics.prometheus]
