version: '3.3'
services:
  consul-leader:
    image: consul:1.10
    command: agent -server -client=0.0.0.0 -bootstrap-expect=1 -ui -ui-content-path=/cluster/consul/ui/
    environment:
      CONSUL_BIND_INTERFACE: eth0
      CONSUL_LOCAL_CONFIG: '{"leave_on_terminate": true}'
    volumes:
     - consul-data-leader:/consul/data
    networks:
     - default
     - traefik-public
    secrets:
     - basic_auth_users
    logging:
      driver: json-file
      options:
        compress: 'true'
        max-file: '3'
        max-size: 10m
    deploy:
      labels:
        traefik.docker.network: traefik-public
        traefik.enable: 'true'
        traefik.frontend.auth.basic.usersFile: /run/secrets/basic_auth_users
        traefik.frontend.rule: PathPrefix:/cluster/consul/
        traefik.port: '8500'
        traefik.tags: traefik-public
      placement:
        constraints:
         - node.labels.consul-host == true
  consul-replica:
    image: consul:1.10
    command: agent -server -client=0.0.0.0 -retry-join=consul-leader
    environment:
      CONSUL_BIND_INTERFACE: eth0
      CONSUL_LOCAL_CONFIG: '{"leave_on_terminate": true}'
    volumes:
     - consul-data-replica:/consul/data
    networks:
     - default
     - traefik-public
    logging:
      driver: json-file
      options:
        compress: 'true'
        max-file: '3'
        max-size: 10m
    deploy:
      replicas: 0
  traefik:
    image: traefik:v1.7
    ports:
     - 80:80
     - 443:443
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
    networks:
     - default
     - traefik-public
    secrets:
     - basic_auth_users
    configs:
     -
      source: traefik-config
      target: /etc/traefik/traefik.toml
    logging:
      driver: json-file
      options:
        compress: 'true'
        max-file: '3'
        max-size: 10m
    deploy:
      labels:
        traefik.docker.network: traefik-public
        traefik.enable: 'true'
        traefik.frontend.auth.basic.usersFile: /run/secrets/basic_auth_users
        traefik.frontend.rule: PathPrefixStrip:/cluster/traefik/
        traefik.port: '8080'
        traefik.tags: traefik-public
      placement:
        constraints:
         - node.labels.consul-host == true
networks:
  default:
    driver: overlay
  traefik-public:
    external: true
volumes:
  consul-data-leader:
    driver: local
  consul-data-replica:
    driver: local
configs:
  traefik-config:
    external: true
secrets:
  basic_auth_users:
    external: true
